In [7]:
import pandas as pd
import requests
import json
from pprint import pprint
import numpy as np
from pandas.io.json import json_normalize

In [8]:
#link to The Movies Data Base API 
url = "https://api.themoviedb.org/3/movie/upcoming?api_key=8bc5a5245af0e94fde2d2ac84dffb856&language=en-US&page=1"

In [9]:
#creating a variable to store the results found in the url above
response = requests.get(url) 
#storing the responses to a new variable, data
data = response.json()
# pprint(data)

In [10]:
#create variables to store the information from the json into a dataframe
id = []
title = []
popularity = []
vote_average = []
vote_count = []
original_language = []
release_date = []

In [11]:
#create for loop that reads through each page of the json response 
num_page = 1
for num_page in range(1, data['total_pages']):
    url = "https://api.themoviedb.org/3/movie/upcoming?api_key=8bc5a5245af0e94fde2d2ac84dffb856&language=en-US&page=1"
    response = requests.get(url).json()

    #for results, append select data to the empty variable arrays above 
    try:
        for x in range(0, len(response['results'])):
            id.append(response['results'][x]['id'])
            popularity.append(response['results'][x]['popularity'])
            vote_average.append(response['results'][x]['vote_average'])
            vote_count.append(response['results'][x]['vote_count'])
            original_language.append(response['results'][x]['original_language'])
            release_date.append(response['results'][x]['release_date'])
   #skip over values that don't exist
    except (KeyError, IndexError):
        print("value doesn't exist")
        
#normalize the json to make sure all variable arrays are the same length and thus can be stored in a pandas dataframe together        
df = pd.json_normalize(response['results'])
df.head(3)

,popularity,vote_count,video,poster_path,id,adult,backdrop_path,original_language,original_title,genre_ids,title,vote_average,overview,release_date
0,413.599,347,False,/uOw5JD8IlD546feZ6oxbIjvN66P.jpg,718444,False,/x4UkhIQuHIJyeeOTdcbZ3t3gBSa.jpg,en,Rogue,"[28, 12, 18, 53]",Rogue,5.8,Battle-hardened O’Hara leads a lively mercenar...,2020-08-20
1,325.261,47,False,/eAUzmhP54bE1vPXaY7FbuZREJlR.jpg,594718,False,/mBbA77FyzhU0Tz9tmbKG8heGmh3.jpg,ru,Спутник,"[878, 18, 27]",Sputnik,6.4,"At the height of the Cold War, a Soviet spacec...",2020-09-10
2,294.239,117,False,/yUFbPtWeDbVR3zmqshOaL5lScyo.jpg,425001,False,/4gKyQ1McHa8ZKDsYoyKQSevF01J.jpg,en,The War with Grandpa,"[35, 10751, 18]",The War with Grandpa,6.0,Peter is thrilled that his Grandpa is coming t...,2020-08-27

In [12]:
#reorganized the columns of the new dataframe 
new_releases_df = df[['id','title','popularity','vote_count','vote_average','release_date','original_language','genre_ids','overview']]

In [13]:
new_releases_df.head(3)

,id,title,popularity,vote_count,vote_average,release_date,original_language,genre_ids,overview
0,718444,Rogue,413.599,347,5.8,2020-08-20,en,"[28, 12, 18, 53]",Battle-hardened O’Hara leads a lively mercenar...
1,594718,Sputnik,325.261,47,6.4,2020-09-10,ru,"[878, 18, 27]","At the height of the Cold War, a Soviet spacec..."
2,425001,The War with Grandpa,294.239,117,6.0,2020-08-27,en,"[35, 10751, 18]",Peter is thrilled that his Grandpa is coming t...

In [ ]:
#now see if you can get a list of movie ids for upcoming releases that also includes at least 3 columns that are the same as above

In [25]:
future_movies_df = new_releases_df[(new_releases_df['release_date'] > '2020-11-14')]
future_movies_df.to_csv("future_movies.csv")
future_movies_df

,id,title,popularity,vote_count,vote_average,release_date,original_language,genre_ids,overview
3,591629,Lady Driver,199.914,0,0.0,2020-12-03,en,[18],When a rebellious teen embarks on a solo summe...
5,611605,1BR,160.884,0,0.0,2020-11-26,en,"[53, 18, 27]",When Sarah lucks into a sweet one-bedroom at A...
8,529203,The Croods: A New Age,105.730,0,0.0,2020-11-19,en,"[12, 14, 10751, 16]","After leaving their cave, the Croods encounter..."
14,521007,Superintelligence,42.938,0,0.0,2020-11-26,en,"[28, 35]",When an all-powerful Superintelligence chooses...
18,458576,Monster Hunter,38.656,0,0.0,2020-12-03,en,"[14, 28, 12]",A portal transports Lt. Artemis and an elite u...