In [1]:
import pandas as pd

#import
movie_data = pd.read_csv('resources/now_playing.csv', low_memory=False)
movie_data.head(10)

,Unnamed: 0,np_id,np_title,genre_id,release_date,vote_count,np_populatrity,original_language,timeframe_end,timeframe_start
0,0,724989,Hard Kill,"[28, 53]",2020-10-23,117,1644.732,en,2020-11-17,2020-09-30
1,1,671039,Rogue City,"[53, 28, 18, 80]",2020-10-30,148,1622.107,fr,2020-11-17,2020-09-30
2,2,531219,Roald Dahl's The Witches,"[14, 10751, 12, 35, 27]",2020-10-26,620,1507.392,en,2020-11-17,2020-09-30
3,3,528085,2067,"[878, 53, 18]",2020-10-01,296,1278.003,en,2020-11-17,2020-09-30
4,4,741074,Once Upon a Snowman,"[16, 10751, 35, 14]",2020-10-23,129,984.986,en,2020-11-17,2020-09-30
5,5,340102,The New Mutants,"[28, 878, 27, 12]",2020-08-26,551,941.338,en,2020-11-17,2020-09-30
6,6,613504,After We Collided,"[10749, 18]",2020-09-02,1695,836.766,en,2020-11-17,2020-09-30
7,7,635302,Demon Slayer: Kimetsu no Yaiba - The Movie: Mu...,"[16, 28, 36, 12, 14, 18]",2020-10-16,64,828.001,ja,2020-11-17,2020-09-30
8,8,560050,Over the Moon,"[16, 12, 10751, 14]",2020-10-16,364,742.496,en,2020-11-17,2020-09-30
9,9,624779,VFW,"[28, 53, 27]",2020-10-14,9,699.114,en,2020-11-17,2020-09-30

In [3]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf_vector = TfidfVectorizer(stop_words='english')
movie_data['genre_id'] = movie_data['genre_id'].fillna('')
tfidf_matrix = tfidf_vector.fit_transform(movie_data['genre_id'])

In [4]:
from sklearn.metrics.pairwise import linear_kernel
sim_matrix = linear_kernel(tfidf_matrix, tfidf_matrix)

In [5]:
indices = pd.Series(movie_data.index, index=movie_data['np_title']).drop_duplicates()
indices[:10]

np_title
Hard Kill                                                  0
Rogue City                                                 1
Roald Dahl's The Witches                                   2
2067                                                       3
Once Upon a Snowman                                        4
The New Mutants                                            5
After We Collided                                          6
Demon Slayer: Kimetsu no Yaiba - The Movie: Mugen Train    7
Over the Moon                                              8
VFW                                                        9
dtype: int64

In [6]:
def movie_recommender(np_title, sim_scores=sim_matrix):
    idx = indices[np_title]
    sim_scores = list(enumerate(sim_matrix[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:11]
    movie_indices = [i[0] for i in sim_scores]
    return movie_data['np_title'].iloc[movie_indices]

In [11]:
movie_recommender('Tenet')

1367                Venom Collection
258                       Occupation
614     The Conspiracy of Dark Falls
0                          Hard Kill
49                          Unhinged
53                         Greenland
147                      The Doorman
893                     Bhajarangi 2
3                               2067
129                              Run
Name: np_title, dtype: object